# Generated by Django 5.1.6 on 2025-02-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='contact_for',
        ),
    ]
