# Generated by Django 5.1.6 on 2025-03-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0006_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='interviewprep',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
