# Generated by Django 5.1.6 on 2025-03-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0007_delete_interviewprep_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='interviewprep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('domain', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('user_ans', models.TextField()),
                ('question', models.TextField()),
                ('suggested_answer', models.TextField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
