# Generated by Django 5.1.6 on 2025-03-12 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewprep',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.job'),
        ),
    ]
